make image_data a required kw arg
this means we don't need to manually raise a runtime error. if
image_data isn't supplied you'll see a sensible python exception
```
TypeError: __init__() missing 1 required keyword-only argument: 'image_data'
```