Add a custom metaclass for JSONModel
This tells Python in which order to run the parent metaclasses when
creating the class.

Without this an error will be raised:
```
TypeError: metaclass conflict: the metaclass of a derived class must be
a (non-strict) subclass of the metaclasses of all its bases
```